//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kohvimasiin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kohviautomaat
    {
        public int kohvi_Id { get; set; }
        public string jooginimi { get; set; }
    
        public virtual Topsejuua Topsejuua { get; set; }
        public virtual Topsepakis Topsepakis { get; set; }
    }
}
